book_library/urls.py
from django.contrib import admin
from django.contrib.auth import login
from django.urls import path
# from . import views
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from catalog.views import BookListView, LoanedBooksByUserListView, renew_book_librarian, BookDetailView

from catalog import views

# router = routers.DefaultRouter()
# router.register(r'Books', BookListView, basename='books')
# router.register(r'LoanedBook', LoanedBooksByUserListView, basename='My-borrowed')
# router.register(r'renew_book_liberian', renew_book_librarian, basename='renew_book_liberian')
# router.register(r'Book-Detail', BookDetailView, basename='Book-Detail')
# router.register('', )
# urlpatterns = router.urls
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('catalog/', include('catalog.urls')),
                  path('', RedirectView.as_view(url='catalog/', permanent=True)),
                  path('accounts/', include('django.contrib.auth.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# path('catalog/', include('catalog.urls')),
# path('book/<int:id>/', views.book_detail, name='book_detail'),
# path('books/', views.BookListView.as_view(), name='books'),
# path('accounts/', include('django.contrib.auth.urls')),
# # path('mybook/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
# path('', RedirectView.as_view(url='catalog/', permanent=True)),
# path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
# path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),

# ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns = [
#                   path('admin/', admin.site.urls),
#                   path('catalog/', include('catalog.urls')),
#                   path('books/', views.BookListView.as_view(), name='books'),
#                   path('accounts/', include('django.contrib.auth.urls')),
#                   path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
#                   path('', RedirectView.as_view(url='catalog/', permanent=True)),
#                   path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
#                   path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
#
#               ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic import RedirectView
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    # path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),

]

urlpatterns += [
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
]

urlpatterns += [
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]
urlpatterns += [
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
]

# urlpatterns += [
#     path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
# ]

catalog/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date


class Genre(models.Model):
    # model representing book genre
    name = models.CharField(max_length=200, help_text='Enter a book genre')

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, unique=True,
                            help_text='13 Character '
                                      '<a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='select a genre for this book')

    # def __init__(self, *args, **kwargs):
    #     super().__init__(args, kwargs)
    #     self.id = None

    def __str__(self):
        return self.author

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this '
                                                                          'particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'on loan'),
        ('a', 'available'),
        ('r', 'reserved')
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        # """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    dob = models.DateTimeField(null=True, blank=True)
    dod = models.DateTimeField('died', null=True, blank=True)

    def get_absolute_url(self):
        # """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        # """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

    class Meta:
        ordering = ['last_name']

catalog/forms.py
import datetime

from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.forms import ModelForm
from catalog.models import BookInstance


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data


class RenewBookModelForm(ModelForm):
    def clean_due_back(self):
        data = self.cleaned_data['due_back']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('New renewal date')}
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).')}

catalog/views.py
from django.http import Http404
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required
from .models import Book, Author, BookInstance, Genre
from django.views import generic, View
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
import datetime
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from catalog.forms import RenewBookForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
# from catalog.models import Author
from .serializers import BookSerializer


# Create your views here.

class BookListView(generic.ListView):
    model = Book
    context_object_name = 'book_list'
    # paginate_by = 2
    template_name = 'catalog/book_list.html'

    def get_queryset(self):
        return Book.objects.all()  # Get 5 books containing the title war

    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        context['some_data'] = 'This is just some data'
        return context


class BookDetailView(generic.DetailView):
    model = Book

    def book_detail_view(request, primary_key):
        books = get_object_or_404(Book, pk=primary_key)
        return render(request, 'catalog/book_detail.html', context={'book': books})


def index(request):
    #  view function for home page view

    # generate counts for some of the main objects
    num_books = Book.objects.all().count()
    num_instance = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'new_books': num_books,
        'new_instance': num_instance,
        'new_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


class MyView(LoginRequiredMixin, PermissionRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
    permission_required = ('catalog.can_mark_returned', 'catalog.can_edit')


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    # Generic class-based view listing books on loan to current user
    model = BookInstance
    template_name = 'catalog/book_instance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    # If this is a POST request then process the Form data
    if request.method == 'POST':
        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed'))

        # If this is a GET (or any other method) create the default form.
        else:
            proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
            form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

        context = {
            'form': form,
            'book_instance': book_instance,
        }

        return render(request, 'catalog/book_renew_liberian.html', context)


class AuthorListView(generic.ListView):
    model = Author
    context_object_name = 'author_list'
    # paginate_by = 2
    template_name = 'catalog/author_list.html'

    def get_queryset(self):
        return Author.objects.all()  # Get 5 books containing the title war

    def get_context_data(self, **kwargs):
        context = super(AuthorListView, self).get_context_data(**kwargs)
        context['some_data'] = 'This is just some data'
        return context


class AuthorDetailView(generic.DetailView):
    model = Author

    def author_detail_view(self, primary_key):
        authors = get_object_or_404(Book, pk=primary_key)
        return render(self, 'catalog/author_detail.html', context={'authors': authors})


class AuthorCreate(CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'dob', 'died']
    initial = {'date_of_death': '11/06/2020'}


class AuthorUpdate(UpdateView):
    model = Author
    fields = '__all__'  # Not recommended (potential security issue if more fields added)


class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')


class BookCreate(CreateView):
    model = Book
    fields = '__all__'

templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author: {{ author }}</h1>
{#    <h4> Books </h4>#}
    {#     <a href="{{ book.author.get_absolute_url }}">{{ author.first_name }}</a>#}
    <p><strong>Firstname:</strong> {{ author.first_name }}</p>
    <p><strong>Lastname:</strong> {{ author.last_name }}</p>
    <p><strong>Date_Of_Birth:</strong> {{ author.dob }}</p>
    <p><strong>Date_Of_Death:</strong> {{ author.dod }}</p>
{#  <p><strong>Genre:</strong> {{ author.genre.all|join:", " }}</p>#}

{#  <div style="margin-left:20px;margin-top:20px">#}
{#    <h4>Copies</h4>#}
{##}
{#    {% for copy in book.bookinstance_set.all %}#}
{#      <hr>#}
{#      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">#}
{#        {{ copy.get_status_display }}#}
{#      </p>#}
{#      {% if copy.status != 'a' %}#}
{#        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>#}
{#      {% endif %}#}
{#      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>#}
{#      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>#}
{#    {% endfor %}#}
{#  </div>#}
{% endblock %}

templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author List</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name}}</a> {{author.last_name}} ({{ author.dod }})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no author in the library.</p>
  {% endif %}
{% endblock %}

templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

 <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p><!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/book_instance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
{% endblock %}

templates/catalog/book_renew_liberian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
         {{ form.as_table }}
        <tr>
  <th><label for="id_renewal_date">Renewal date:</label></th>
    <td>
      <ul class="errorlist">
        <li>Invalid date - renewal in past</li>
      </ul>
      <input id="id_renewal_date" name="renewal_date" type="text" value="2015-11-08" required>
      <br>
      <span class="helptext">Enter date between now and 4 weeks (default 3 weeks).</span>
    </td>
</tr>
        {#    {{ form.as_ul }}#}
{#    {{ form.renewal_date }}#}
{#    {{ form.renewal_date.errors }}#}
{#    {{ form.renewal_date.id_for_label }}#}
{#    {{ form.renewal_date.help_text }}#}
{#    {% if perms.catalog.can_mark_returned %}#}
{#       - <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>#}
{#    {% endif %}#}

    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}